{
    ENV: os.environ.get('ENV', default='uat'),
    BROWSER: os.environ.get('BROWSER', default='chrome'),
    BASE_URL: https://www.cosmosid.com/,
        LOGIN_PAGE: https://app.cosmosid.com/login,
        port: 1542,
        HOME_PATH: os.path.abspath(os.path.join(os.path.dirname(__file__), os.pardir)),
    ADMIN_BASE_URL: https://app.cosmosid.com/admin,
        general_user: None,
        config_path: Path.home()/'PycharmProjects'/'gl-procamp_PythonProject'/'config',
        config_path_json: config_path/'config'/f'.js',
        config_path_yaml: config_path/'config'/f'.yaml',
        SUPPORTED_BROWSERS: [ chrome, firefox, edge, opera],
        defaults: {
            "ENV": 'uat',
            "BROWSER": 'chrome',
            "BASE_URL": "https://www.cosmosid.com",
            "LOGIN_PAGE": "https://app.cosmosid.com/login",
            "SUPPORTED_BROWSERS": [ "chrome", "firefox", "edge", "opera"]
            }